---
- hosts: webservers
  vars: 
    worker_processes: 4
    num_cpus: 2
    max_open_file: 65536
    root: /data
  remote_user: root
  tasks:
  - name: ensure nginx is at latest version
    yum: pkg=nginx state=latest
  
  - name: wrtie the nginx config file
    template: src=/home/zhaifg/development/playbook/nginx/nginx2.conf  dest=/etc/nginx/nginx.conf
    notify:
      - restart nginx
   
  - name: ensure nginx is running
    service: name=nginx state=started

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
 

